name: appnation_case
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cross_connectivity: ^3.0.5
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
